package mt.composite;

public enum ComponentType {
    TEXT, SENTENCE, WORD, NUMBER, SEMICOLON, RESERVED_WORD, RESERVED_CHARACTER, MATH_OPERATOR,
    LEFT_PARENTHESES, RIGHT_PARENTHESES, OPEN_CURLY_BRACKET, CLOSED_CURLY_BRACKET
}
